// MANAGE - GET Class
export const REQ_FOR_GET_CLASS_PROGRESS = "REQ_FOR_GET_CLASS_PROGRESS"
export const REQ_FOR_GET_CLASS_SUCCESS = "REQ_FOR_GET_CLASS_SUCCESS"
export const REQ_FOR_GET_CLASS_ERROR = "REQ_FOR_GET_CLASS_ERROR"

// MANAGE - Craete Class
export const REQ_FOR_POST_CREATE_CLASS_PROGRESS = "REQ_FOR_POST_CREATE_CLASS_PROGRESS"
export const REQ_FOR_POST_CREATE_CLASS_SUCCESS = "REQ_FOR_POST_CREATE_CLASS_SUCCESS"
export const REQ_FOR_POST_CREATE_CLASS_ERROR = "REQ_FOR_POST_CREATE_CLASS_ERROR"
export const REQ_FOR_POST_CREATE_CLASS_DUPLICATE = "REQ_FOR_POST_CREATE_CLASS_DUPLICATE"

// MANAGE - Assign Class
export const REQ_FOR_PATCH_ASSIGN_CLASS_PROGRESS = "REQ_FOR_PATCH_ASSIGN_CLASS_PROGRESS"
export const REQ_FOR_PATCH_ASSIGN_CLASS_SUCCESS = "REQ_FOR_PATCH_ASSIGN_CLASS_SUCCESS"
export const REQ_FOR_PATCH_ASSIGN_CLASS_ERROR = "REQ_FOR_PATCH_ASSIGN_CLASS_ERROR"
export const REQ_FOR_PATCH_ASSIGN_CLASS_DUPLICATE = "REQ_FOR_PATCH_ASSIGN_CLASS_DUPLICATE"

// MANAGE - unassign Class
export const REQ_FOR_UNASSIGN_CLASS_PROGRESS = "REQ_FOR_UNASSIGN_CLASS_PROGRESS"
export const REQ_FOR_UNASSIGN_CLASS_SUCCESS = "REQ_FOR_UNASSIGN_CLASS_SUCCESS"
export const REQ_FOR_UNASSIGN_CLASS_ERROR = "REQ_FOR_UNASSIGN_CLASS_ERROR"


// MANAGE - Delete Class
export const REQ_FOR_DELETE_CLASS_PROGRESS = "REQ_FOR_DELETE_CLASS_PROGRESS"
export const REQ_FOR_DELETE_CLASS_SUCCESS = "REQ_FOR_DELETE_CLASS_SUCCESS"
export const REQ_FOR_DELETE_CLASS_ERROR = "REQ_FOR_DELETE_CLASS_ERROR"

// MANAGE - Update Class
export const REQ_FOR_UPDATE_CLASS_PROGRESS = "REQ_FOR_UPDATE_CLASS_PROGRESS"
export const REQ_FOR_UPDATE_CLASS_SUCCESS = "REQ_FOR_UPDATE_CLASS_SUCCESS"
export const REQ_FOR_UPDATE_CLASS_ERROR = "REQ_FOR_UPDATE_CLASS_ERROR"
export const REQ_FOR_UPDATE_CLASS_DUPLICATE = "REQ_FOR_UPDATE_CLASS_DUPLICATE"

//------------------------class Coordinator----------------------------//

// MANAGE - GET Class Coordinators
export const REQ_FOR_GET_CC_PROGRESS = "REQ_FOR_GET_CC_PROGRESS"
export const REQ_FOR_GET_CC_SUCCESS = "REQ_FOR_GET_CC_SUCCESS"
export const REQ_FOR_GET_CC_ERROR = "REQ_FOR_GET_CC_ERROR"

// MANAGE - Create Class Coordinators
export const REQ_FOR_POST_CREATE_CC_PROGRESS = "REQ_FOR_POST_CREATE_CC_PROGRESS"
export const REQ_FOR_POST_CREATE_CC_SUCCESS = "REQ_FOR_POST_CREATE_CC_SUCCESS"
export const REQ_FOR_POST_CREATE_CC_ERROR = "REQ_FOR_POST_CREATE_CC_ERROR"
export const REQ_FOR_POST_CREATE_CC_DUPLICATE = "REQ_FOR_POST_CREATE_CC_DUPLICATE"

// MANAGE - update Class Coordinators
export const REQ_FOR_PATCH_CC_PROGRESS = "REQ_FOR_PATCH_CC_PROGRESS"
export const REQ_FOR_PATCH_CC_SUCCESS = "REQ_FOR_PATCH_CC_SUCCESS"
export const REQ_FOR_PATCH_CC_ERROR = "REQ_FOR_PATCH_CC_ERROR"
export const REQ_FOR_PATCH_CC_DUPLICATE = "REQ_FOR_PATCH_CC_DUPLICATE"


// MANAGE - Upload CSV Class Coordinators
export const REQ_FOR_POST_UPLOAD_CC_CSV_PROGRESS = "REQ_FOR_POST_UPLOAD_CC_CSV_PROGRESS"
export const REQ_FOR_POST_UPLOAD_CC_CSV_SUCCESS = "REQ_FOR_POST_UPLOAD_CC_CSV_SUCCESS"
export const REQ_FOR_POST_UPLOAD_CC_CSV_ERROR = "REQ_FOR_POST_UPLOAD_CC_CSV_ERROR"
export const REQ_FOR_POST_UPLOAD_CC_CSV_DUPLICATE = "REQ_FOR_POST_UPLOAD_CC_CSV_DUPLICATE"

// MANAGE - Delete Class Coordinator
export const REQ_FOR_DELETE_CC_PROGRESS = "REQ_FOR_DELETE_CC_PROGRESS"
export const REQ_FOR_DELETE_CC_SUCCESS = "REQ_FOR_DELETE_CC_SUCCESS"
export const REQ_FOR_DELETE_CC_ERROR = "REQ_FOR_DELETE_CC_ERROR"


// ----------------------- REQ BY SCHOOL --------------------
// GET REQ BY CLASS
export const REQ_FOR_GET_ACTIVITY_BY_SCHOOL_APC_PROGRESS = "REQ_FOR_GET_ACTIVITY_BY_SCHOOL_APC_PROGRESS"
export const REQ_FOR_GET_ACTIVITY_BY_SCHOOL_APC_SUCCESS = "REQ_FOR_GET_ACTIVITY_BY_SCHOOL_APC_SUCCESS"
export const REQ_FOR_GET_ACTIVITY_BY_SCHOOL_APC_ERROR = "REQ_FOR_GET_ACTIVITY_BY_SCHOOL_APC_ERROR"


//  ------------------ Status Chnage -------------------------------
// APC Status Chnaged
// POST Apc -> Status Chnaged
export const REQ_FOR_PATCH_APC_STATUS_CHANGE_PROGRESS = "REQ_FOR_PATCH_APC_STATUS_CHANGE_PROGRESS"
export const REQ_FOR_PATCH_APC_STATUS_CHANGE_SUCCESS = "REQ_FOR_PATCH_APC_STATUS_CHANGE_SUCCESS"
export const REQ_FOR_PATCH_APC_STATUS_CHANGE_ERROR = "REQ_FOR_PATCH_APC_STATUS_CHANGE_ERROR"

//-------------------------manage student section--------------------//

//upload CSV
export const REQ_FOR_UPLOAD_CSV_STUDENT = "REQ_FOR_UPLOAD_CSV_STUDENT"


// MANAGE - GET All Student
export const REQ_FOR_GET_ALL_STUDENT_PROGRESS = "REQ_FOR_GET_ALL_STUDENT_PROGRESS"
export const REQ_FOR_GET_ALL_STUDENT_SUCCESS = "REQ_FOR_GET_ALL_STUDENT_SUCCESS"
export const REQ_FOR_GET_ALL_STUDENT_ERROR = "REQ_FOR_GET_ALL_STUDENT_ERROR"

// MANAGE - Upload CSV Student
export const REQ_FOR_POST_UPLOAD_STUDENT_CSV_PROGRESS = "REQ_FOR_POST_UPLOAD_STUDENT_CSV_PROGRESS"
export const REQ_FOR_POST_UPLOAD_STUDENT_CSV_SUCCESS = "REQ_FOR_POST_UPLOAD_STUDENT_CSV_SUCCESS"
export const REQ_FOR_POST_UPLOAD_STUDENT_CSV_ERROR = "REQ_FOR_POST_UPLOAD_STUDENT_CSV_ERROR"
export const REQ_FOR_POST_UPLOAD_STUDENT_CSV_DUPLICATE = "REQ_FOR_POST_UPLOAD_STUDENT_CSV_DUPLICATE"


// MANAGE - Craete Student
export const REQ_FOR_POST_CREATE_STUDENT_PROGRESS = "REQ_FOR_POST_CREATE_STUDENT_PROGRESS"
export const REQ_FOR_POST_CREATE_STUDENT_SUCCESS = "REQ_FOR_POST_CREATE_STUDENT_SUCCESS"
export const REQ_FOR_POST_CREATE_STUDENT_ERROR = "REQ_FOR_POST_CREATE_STUDENT_ERROR"
export const REQ_FOR_POST_CREATE_STUDENT_DUPLICATE = "REQ_FOR_POST_CREATE_STUDENT_DUPLICATE"

// MANAGE - Craete Student
export const REQ_FOR_PATCH_STUDENT_PROGRESS = "REQ_FOR_PATCH_STUDENT_PROGRESS"
export const REQ_FOR_PATCH_STUDENT_SUCCESS = "REQ_FOR_PATCH_STUDENT_SUCCESS"
export const REQ_FOR_PATCH_STUDENT_ERROR = "REQ_FOR_PATCH_STUDENT_ERROR"
export const REQ_FOR_PATCH_STUDENT_DUPLICATE = "REQ_FOR_PATCH_STUDENT_DUPLICATE"


// MANAGE - Delete Student
export const REQ_FOR_DELETE_STUDENT_PROGRESS = "REQ_FOR_DELETE_STUDENT_PROGRESS"
export const REQ_FOR_DELETE_STUDENT_SUCCESS = "REQ_FOR_DELETE_STUDENT_SUCCESS"
export const REQ_FOR_DELETE_STUDENT_ERROR = "REQ_FOR_DELETE_STUDENT_ERROR"

// APC Profile
export const REQ_FOR_GET_APC_PROFILE_PROGRESS = "REQ_FOR_GET_APC_PROFILE_PROGRESS"
export const REQ_FOR_GET_APC_PROFILE_SUCCESS = "REQ_FOR_GET_APC_PROFILE_SUCCESS"
export const REQ_FOR_GET_APC_PROFILE_ERROR = "REQ_FOR_GET_APC_PROFILE_ERROR"



// PATCH Apc Change Password
export const REQ_FOR_PATCH_APC_PASSWORD_PROGRESS = "REQ_FOR_PATCH_APC_PASSWORD_PROGRESS"
export const REQ_FOR_PATCH_APC_PASSWORD_SUCCESS = "REQ_FOR_PATCH_APC_PASSWORD_SUCCESS"
export const REQ_FOR_PATCH_APC_PASSWORD_ERROR = "REQ_FOR_PATCH_APC_PASSWORD_ERROR"
export const REQ_FOR_PATCH_APC_PASSWORD_DUPLICATE = "REQ_FOR_PATCH_APC_PASSWORD_DUPLICATE"