// GET APC Data (GET APC data)
// Manage  -- APC
export const REQ_FOR_GET_APC_PROGRESS = "REQ_FOR_GET_APC_PROGRESS"
export const REQ_FOR_GET_APC_SUCCESS = "REQ_FOR_GET_APC_SUCCESS"
export const REQ_FOR_GET_APC_ERROR = "REQ_FOR_GET_APC_ERROR"

// P (POST APC data)
export const REQ_FOR_POST_APC_PROGRESS = "REQ_FOR_POST_APC_PROGRESS"
export const REQ_FOR_POST_APC_SUCCESS = "REQ_FOR_POST_APC_SUCCESS"
export const REQ_FOR_POST_APC_ERROR = "REQ_FOR_POST_APC_ERROR"
export const REQ_FOR_POST_APC_DUPLICATE = "REQ_FOR_POST_APC_DUPLICATE"



// PATCH Coordinators Data (POST APC data)
export const REQ_FOR_PATCH_APC_PROGRESS = "REQ_FOR_PATCH_APC_PROGRESS"
export const REQ_FOR_PATCH_APC_SUCCESS = "REQ_FOR_PATCH_APC_SUCCESS"
export const REQ_FOR_PATCH_APC_ERROR = "REQ_FOR_PATCH_APC_ERROR"
export const REQ_FOR_PATCH_APC_DUPLICATE = "REQ_FOR_PATCH_APC_DUPLICATE"


// DELETE (DELETE APC data)
export const REQ_FOR_DELETE_APC_PROGRESS = "REQ_FOR_DELETE_APC_PROGRESS"
export const REQ_FOR_DELETE_APC_SUCCESS = "REQ_FOR_DELETE_APC_SUCCESS"
export const REQ_FOR_DELETE_APC_ERROR = "REQ_FOR_DELETE_APC_ERROR"
export const REQ_FOR_DELETE_APC_DUPLICATE = "REQ_FOR_DELETE_APC_DUPLICATE"



// GET Instadmin Profile
export const REQ_FOR_GET_INSTADMIN_PROFILE_PROGRESS = "REQ_FOR_GET_INSTADMIN_PROFILE_PROGRESS"
export const REQ_FOR_GET_INSTADMIN_PROFILE_SUCCESS = "REQ_FOR_GET_INSTADMIN_PROFILE_SUCCESS"
export const REQ_FOR_GET_INSTADMIN_PROFILE_ERROR = "REQ_FOR_GET_INSTADMIN_PROFILE_ERROR"

// Activity req Selection --------------

// GET

export const REQ_FOR_GET_HEADING_TO_SCHOOL_PROGRESS = "REQ_FOR_GET_HEADING_TO_SCHOOL_PROGRESS"
export const REQ_FOR_GET_HEADING_TO_SCHOOL_SUCCESS = "REQ_FOR_GET_HEADING_TO_SCHOOL_SUCCESS"
export const REQ_FOR_GET_HEADING_TO_SCHOOL_ERROR = "REQ_FOR_GET_HEADING_TO_SCHOOL_ERROR"

// Patch --> Assign to School
export const REQ_FOR_PATCH_HEADING_TO_SCHOOL_PROGRESS = "REQ_FOR_PATCH_HEADING_TO_SCHOOL_PROGRESS"
export const REQ_FOR_PATCH_HEADING_TO_SCHOOL_SUCCESS = "REQ_FOR_PATCH_HEADING_TO_SCHOOL_SUCCESS"
export const REQ_FOR_PATCH_HEADING_TO_SCHOOL_ERROR = "REQ_FOR_PATCH_HEADING_TO_SCHOOL_ERROR"
export const REQ_FOR_PATCH_HEADING_TO_SCHOOL_DUPLICATE = "REQ_FOR_PATCH_HEADING_TO_SCHOOL_DUPLICATE"

// Patch --> Delete to school
export const REQ_FOR_PATCH_SCHOOL_TO_HEADING_PROGRESS = "REQ_FOR_PATCH_SCHOOL_TO_HEADING_PROGRESS"
export const REQ_FOR_PATCH_SCHOOL_TO_HEADING_SUCCESS = "REQ_FOR_PATCH_SCHOOL_TO_HEADING_SUCCESS"
export const REQ_FOR_PATCH_SCHOOL_TO_HEADING_ERROR = "REQ_FOR_PATCH_SCHOOL_TO_HEADING_ERROR"
export const REQ_FOR_PATCH_SCHOOL_TO_HEADING_DUPLICATE = "REQ_FOR_PATCH_SCHOOL_TO_HEADING_DUPLICATE"



// Add Activity Request -----------------------------------------------------------

// Manage  -- GET HEading
export const REQ_FOR_GET_ACTIVITY_PROGRESS = "REQ_FOR_GET_ACTIVITY_PROGRESS"
export const REQ_FOR_GET_ACTIVITY_SUCCESS = "REQ_FOR_GET_ACTIVITY_SUCCESS"
export const REQ_FOR_GET_ACTIVITY_ERROR = "REQ_FOR_GET_ACTIVITY_ERROR"

// Manage  -- DELETE HEading
export const REQ_FOR_DELETE_HEADING_PROGRESS = "REQ_FOR_DELETE_HEADING_PROGRESS"
export const REQ_FOR_DELETE_HEADING_SUCCESS = "REQ_FOR_DELETE_HEADING_SUCCESS"
export const REQ_FOR_DELETE_HEADING_ERROR = "REQ_FOR_DELETE_HEADING_ERROR"

// MANAGE - Craete Heading
export const REQ_FOR_POST_CREATE_ACTIVITY_PROGRESS = "REQ_FOR_POST_CREATE_ACTIVITY_PROGRESS"
export const REQ_FOR_POST_CREATE_ACTIVITY_SUCCESS = "REQ_FOR_POST_CREATE_ACTIVITY_SUCCESS"
export const REQ_FOR_POST_CREATE_ACTIVITY_ERROR = "REQ_FOR_POST_CREATE_ACTIVITY_ERROR"
export const REQ_FOR_POST_CREATE_ACTIVITY_DUPLICATE = "REQ_FOR_POST_CREATE_ACTIVITY_DUPLICATE"




// PATCH INSTADMIN Change Password
export const REQ_FOR_PATCH_INSTADMIN_PASSWORD_PROGRESS = "REQ_FOR_PATCH_INSTADMIN_PASSWORD_PROGRESS"
export const REQ_FOR_PATCH_INSTADMIN_PASSWORD_SUCCESS = "REQ_FOR_PATCH_INSTADMIN_PASSWORD_SUCCESS"
export const REQ_FOR_PATCH_INSTADMIN_PASSWORD_ERROR = "REQ_FOR_PATCH_INSTADMIN_PASSWORD_ERROR"
export const REQ_FOR_PATCH_INSTADMIN_PASSWORD_DUPLICATE = "REQ_FOR_PATCH_INSTADMIN_PASSWORD_DUPLICATE"