// GET student Activity
export const REQ_FOR_LOGIN_PROGRESS = "REQ_FOR_LOGIN_PROGRESS"
export const REQ_FOR_LOGIN_SUCCESS = "REQ_FOR_LOGIN_SUCCESS"
export const REQ_FOR_LOGIN_ERROR = "REQ_FOR_LOGIN_ERROR"
export const REQ_FOR_LOGIN_FAILED = "REQ_FOR_LOGIN_FAILED"