// GET student Activity
export const REQ_FOR_GET_STUDENT_ACTIVITY_PROGRESS = "REQ_FOR_GET_STUDENT_ACTIVITY_PROGRESS"
export const REQ_FOR_GET_STUDENT_ACTIVITY_SUCCESS = "REQ_FOR_GET_STUDENT_ACTIVITY_SUCCESS"
export const REQ_FOR_GET_STUDENT_ACTIVITY_ERROR = "REQ_FOR_GET_STUDENT_ACTIVITY_ERROR"

// POST student Activity
export const REQ_FOR_POST_STUDENT_ACTIVITY_PROGRESS = "REQ_FOR_POST_STUDENT_ACTIVITY_PROGRESS"
export const REQ_FOR_POST_STUDENT_ACTIVITY_SUCCESS = "REQ_FOR_POST_STUDENT_ACTIVITY_SUCCESS"
export const REQ_FOR_POST_STUDENT_ACTIVITY_ERROR = "REQ_FOR_POST_STUDENT_ACTIVITY_ERROR"
export const REQ_FOR_POST_STUDENT_ACTIVITY_DUPLICATE = "REQ_FOR_POST_STUDENT_ACTIVITY_DUPLICATE"

// PATCH student Activity
export const REQ_FOR_PATCH_STUDENT_ACTIVITY_PROGRESS = "REQ_FOR_PATCH_STUDENT_ACTIVITY_PROGRESS"
export const REQ_FOR_PATCH_STUDENT_ACTIVITY_SUCCESS = "REQ_FOR_PATCH_STUDENT_ACTIVITY_SUCCESS"
export const REQ_FOR_PATCH_STUDENT_ACTIVITY_ERROR = "REQ_FOR_PATCH_STUDENT_ACTIVITY_ERROR"
export const REQ_FOR_PATCH_STUDENT_ACTIVITY_DUPLICATE = "REQ_FOR_PATCH_STUDENT_ACTIVITY_DUPLICATE"

// DELETE student Activity
export const REQ_FOR_DELETE_STUDENT_ACTIVITY_PROGRESS = "REQ_FOR_DELETE_STUDENT_ACTIVITY_PROGRESS"
export const REQ_FOR_DELETE_STUDENT_ACTIVITY_SUCCESS = "REQ_FOR_DELETE_STUDENT_ACTIVITY_SUCCESS"
export const REQ_FOR_DELETE_STUDENT_ACTIVITY_ERROR = "REQ_FOR_DELETE_STUDENT_ACTIVITY_ERROR"

// GET -- GET HEading
export const REQ_FOR_GET_HEADING_PROGRESS = "REQ_FOR_GET_HEADING_PROGRESS"
export const REQ_FOR_GET_HEADING_SUCCESS = "REQ_FOR_GET_HEADING_SUCCESS"
export const REQ_FOR_GET_HEADING_ERROR = "REQ_FOR_GET_HEADING_ERROR"

// Student Profile Details
// GET student Profile
export const REQ_FOR_GET_STUDENT_PROFILE_PROGRESS = "REQ_FOR_GET_STUDENT_PROFILE_PROGRESS"
export const REQ_FOR_GET_STUDENT_PROFILE_SUCCESS = "REQ_FOR_GET_STUDENT_PROFILE_SUCCESS"
export const REQ_FOR_GET_STUDENT_PROFILE_ERROR = "REQ_FOR_GET_STUDENT_PROFILE_ERROR"


// PATCH student Change Password
export const REQ_FOR_PATCH_STUDENT_PASSWORD_PROGRESS = "REQ_FOR_PATCH_STUDENT_PASSWORD_PROGRESS"
export const REQ_FOR_PATCH_STUDENT_PASSWORD_SUCCESS = "REQ_FOR_PATCH_STUDENT_PASSWORD_SUCCESS"
export const REQ_FOR_PATCH_STUDENT_PASSWORD_ERROR = "REQ_FOR_PATCH_STUDENT_PASSWORD_ERROR"
export const REQ_FOR_PATCH_STUDENT_PASSWORD_DUPLICATE = "REQ_FOR_PATCH_STUDENT_PASSWORD_DUPLICATE"