// GET student Activity
export const REQ_FOR_LOGIN_PROGRESS_APC = "REQ_FOR_LOGIN_PROGRESS_APC"
export const REQ_FOR_LOGIN_SUCCESS_APC = "REQ_FOR_LOGIN_SUCCESS_APC"
export const REQ_FOR_LOGIN_ERROR_APC = "REQ_FOR_LOGIN_ERROR_APC"
export const REQ_FOR_LOGIN_FAILED_APC = "REQ_FOR_LOGIN_FAILED_APC"