// GET school Data
// Manage  -- School
export const REQ_FOR_GET_SCHOOL_PROGRESS = "REQ_FOR_GET_SCHOOL_PROGRESS"
export const REQ_FOR_GET_SCHOOL_SUCCESS = "REQ_FOR_GET_SCHOOL_SUCCESS"
export const REQ_FOR_GET_SCHOOL_ERROR = "REQ_FOR_GET_SCHOOL_ERROR"

// MANAGE - Craete School
export const REQ_FOR_POST_CREATE_SCHOOL_PROGRESS = "REQ_FOR_POST_CREATE_SCHOOL_PROGRESS"
export const REQ_FOR_POST_CREATE_SCHOOL_SUCCESS = "REQ_FOR_POST_CREATE_SCHOOL_SUCCESS"
export const REQ_FOR_POST_CREATE_SCHOOL_ERROR = "REQ_FOR_POST_CREATE_SCHOOL_ERROR"
export const REQ_FOR_POST_CREATE_SCHOOL_DUPLICATE = "REQ_FOR_POST_CREATE_SCHOOL_DUPLICATE"

// MANAGE - Patch School
export const REQ_FOR_PATCH_SCHOOL_PROGRESS = "REQ_FOR_PATCH_SCHOOL_PROGRESS"
export const REQ_FOR_PATCH_SCHOOL_SUCCESS = "REQ_FOR_PATCH_SCHOOL_SUCCESS"
export const REQ_FOR_PATCH_SCHOOL_ERROR = "REQ_FOR_PATCH_SCHOOL_ERROR"
export const REQ_FOR_PATCH_SCHOOL_DUPLICATE = "REQ_FOR_PATCH_SCHOOL_DUPLICATE"

// MANAGE - Delete SChool
export const REQ_FOR_DELETE_SCHOOL_PROGRESS = "REQ_FOR_DELETE_SCHOOL_PROGRESS"
export const REQ_FOR_DELETE_SCHOOL_SUCCESS = "REQ_FOR_DELETE_SCHOOL_SUCCESS"
export const REQ_FOR_DELETE_SCHOOL_ERROR = "REQ_FOR_DELETE_SCHOOL_ERROR"

//-----------------------------heading section-----------------------//

// Manage  -- GET HEading
export const REQ_FOR_GET_HEADING_PROGRESS_COE = "REQ_FOR_GET_HEADING_PROGRESS_COE"
export const REQ_FOR_GET_HEADING_SUCCESS_COE = "REQ_FOR_GET_HEADING_SUCCESS_COE"
export const REQ_FOR_GET_HEADING_ERROR_COE = "REQ_FOR_GET_HEADING_ERROR_COE"

// MANAGE - Craete Heading
export const REQ_FOR_POST_CREATE_HEADING_PROGRESS = "REQ_FOR_POST_CREATE_HEADING_PROGRESS"
export const REQ_FOR_POST_CREATE_HEADING_SUCCESS = "REQ_FOR_POST_CREATE_HEADING_SUCCESS"
export const REQ_FOR_POST_CREATE_HEADING_ERROR = "REQ_FOR_POST_CREATE_HEADING_ERROR"
export const REQ_FOR_POST_CREATE_HEADING_DUPLICATE = "REQ_FOR_POST_CREATE_HEADING_DUPLICATE"

//--------------------------------Dean section-------------------//

// Manage  -- DEAN
export const REQ_FOR_GET_DEAN_PROGRESS = "REQ_FOR_GET_DEAN_PROGRESS"
export const REQ_FOR_GET_DEAN_SUCCESS = "REQ_FOR_GET_DEAN_SUCCESS"
export const REQ_FOR_GET_DEAN_ERROR = "REQ_FOR_GET_DEAN_ERROR"

// MANAGE - Craete DEAN
export const REQ_FOR_POST_CREATE_DEAN_PROGRESS = "REQ_FOR_POST_CREATE_DEAN_PROGRESS"
export const REQ_FOR_POST_CREATE_DEAN_SUCCESS = "REQ_FOR_POST_CREATE_DEAN_SUCCESS"
export const REQ_FOR_POST_CREATE_DEAN_ERROR = "REQ_FOR_POST_CREATE_DEAN_ERROR"
export const REQ_FOR_POST_CREATE_DEAN_DUPLICATE = "REQ_FOR_POST_CREATE_DEAN_DUPLICATE"

// MANAGE - Patch DEAN
export const REQ_FOR_PATCH_DEAN_PROGRESS = "REQ_FOR_PATCH_DEAN_PROGRESS"
export const REQ_FOR_PATCH_DEAN_SUCCESS = "REQ_FOR_PATCH_DEAN_SUCCESS"
export const REQ_FOR_PATCH_DEAN_ERROR = "REQ_FOR_PATCH_DEAN_ERROR"
export const REQ_FOR_PATCH_DEAN_DUPLICATE = "REQ_FOR_PATCH_DEAN_DUPLICATE"

// MANAGE - Delete DEAN
export const REQ_FOR_DELETE_DEAN_PROGRESS = "REQ_FOR_DELETE_DEAN_PROGRESS"
export const REQ_FOR_DELETE_DEAN_SUCCESS = "REQ_FOR_DELETE_DEAN_SUCCESS"
export const REQ_FOR_DELETE_DEAN_ERROR = "REQ_FOR_DELETE_DEAN_ERROR"





// PATCH COE Change Password
export const REQ_FOR_PATCH_COE_PASSWORD_PROGRESS = "REQ_FOR_PATCH_COE_PASSWORD_PROGRESS"
export const REQ_FOR_PATCH_COE_PASSWORD_SUCCESS = "REQ_FOR_PATCH_COE_PASSWORD_SUCCESS"
export const REQ_FOR_PATCH_COE_PASSWORD_ERROR = "REQ_FOR_PATCH_COE_PASSWORD_ERROR"
export const REQ_FOR_PATCH_COE_PASSWORD_DUPLICATE = "REQ_FOR_PATCH_COE_PASSWORD_DUPLICATE"




// COE Profile
export const REQ_FOR_GET_COE_PROFILE_PROGRESS = "REQ_FOR_GET_COE_PROFILE_PROGRESS"
export const REQ_FOR_GET_COE_PROFILE_SUCCESS = "REQ_FOR_GET_COE_PROFILE_SUCCESS"
export const REQ_FOR_GET_COE_PROFILE_ERROR = "REQ_FOR_GET_COE_PROFILE_ERROR"
