// GET student Activity
export const REQ_FOR_LOGIN_PROGRESS_FACULTY = "REQ_FOR_LOGIN_PROGRESS_FACULTY"
export const REQ_FOR_LOGIN_SUCCESS_FACULTY = "REQ_FOR_LOGIN_SUCCESS_FACULTY"
export const REQ_FOR_LOGIN_ERROR_FACULTY = "REQ_FOR_LOGIN_ERROR_FACULTY"
export const REQ_FOR_LOGIN_FAILED_FACULTY = "REQ_FOR_LOGIN_FAILED_FACULTY"