// Request

// GET REQ BY CLASS
export const REQ_FOR_GET_ACTIVITY_BYCLASS_FACULTY_PROGRESS = "REQ_FOR_GET_ACTIVITY_BYCLASS_FACULTY_PROGRESS"
export const REQ_FOR_GET_ACTIVITY_BYCLASS_FACULTY_SUCCESS = "REQ_FOR_GET_ACTIVITY_BYCLASS_FACULTY_SUCCESS"
export const REQ_FOR_GET_ACTIVITY_BYCLASS_FACULTY_ERROR = "REQ_FOR_GET_ACTIVITY_BYCLASS_FACULTY_ERROR"

// Faculty Profile Details
// GET faculty Profile
export const REQ_FOR_GET_FACULTY_PROFILE_PROGRESS = "REQ_FOR_GET_FACULTY_PROFILE_PROGRESS"
export const REQ_FOR_GET_FACULTY_PROFILE_SUCCESS = "REQ_FOR_GET_FACULTY_PROFILE_SUCCESS"
export const REQ_FOR_GET_FACULTY_PROFILE_ERROR = "REQ_FOR_GET_FACULTY_PROFILE_ERROR"


// Faculty Status Chnaged
// POST faculty -> Status Chnaged
export const REQ_FOR_PATCH_FACULTY_STATUS_CHANGE_PROGRESS = "REQ_FOR_PATCH_FACULTY_STATUS_CHANGE_PROGRESS"
export const REQ_FOR_PATCH_FACULTY_STATUS_CHANGE_SUCCESS = "REQ_FOR_PATCH_FACULTY_STATUS_CHANGE_SUCCESS"
export const REQ_FOR_PATCH_FACULTY_STATUS_CHANGE_ERROR = "REQ_FOR_PATCH_FACULTY_STATUS_CHANGE_ERROR"