// GET student Activity
export const REQ_FOR_LOGIN_PROGRESS_COE = "REQ_FOR_LOGIN_PROGRESS_COE"
export const REQ_FOR_LOGIN_SUCCESS_COE = "REQ_FOR_LOGIN_SUCCESS_COE"
export const REQ_FOR_LOGIN_ERROR_COE = "REQ_FOR_LOGIN_ERROR_COE"
export const REQ_FOR_LOGIN_FAILED_COE = "REQ_FOR_LOGIN_FAILED_COE"