// GET student Activity
export const REQ_FOR_LOGIN_PROGRESS_ADMIN = "REQ_FOR_LOGIN_PROGRESS_ADMIN"
export const REQ_FOR_LOGIN_SUCCESS_ADMIN = "REQ_FOR_LOGIN_SUCCESS_ADMIN"
export const REQ_FOR_LOGIN_ERROR_ADMIN = "REQ_FOR_LOGIN_ERROR_ADMIN"
export const REQ_FOR_LOGIN_FAILED_ADMIN = "REQ_FOR_LOGIN_FAILED_ADMIN"